return {
  "romgrk/barbar.nvim",
  lazy = false,
  dependencies = {
    { "lewis6991/gitsigns.nvim", keys = { { "<leader>gs", "<cmd>Gitsigns<cr>" } } },
    "nvim-tree/nvim-web-devicons",
  },
  keys = {
    { "<Tab>", "<cmd>BufferNext<cr>", desc = "Next buffer", silent = true },
    { "<S-Tab>", "<cmd>BufferPrevious<cr>", desc = "Previous buffer", silent = true },
    { "<A-,>", "<cmd>BufferPrevious<cr>", desc = "Previous buffer", silent = true },
    { "<A-.>", "<cmd>BufferNext<cr>", desc = "Next buffer", silent = true },
    { "<A-<>", "<cmd>BufferMovePrevious<cr>", desc = "Move buffer left", silent = true },
    { "<A->>", "<cmd>BufferMoveNext<cr>", desc = "Move buffer right", silent = true },
    { "<A-1>", "<cmd>BufferGoto 1<cr>", desc = "Buffer 1", silent = true },
    { "<A-2>", "<cmd>BufferGoto 2<cr>", desc = "Buffer 2", silent = true },
    { "<A-3>", "<cmd>BufferGoto 3<cr>", desc = "Buffer 3", silent = true },
    { "<A-4>", "<cmd>BufferGoto 4<cr>", desc = "Buffer 4", silent = true },
    { "<A-5>", "<cmd>BufferGoto 5<cr>", desc = "Buffer 5", silent = true },
    { "<A-6>", "<cmd>BufferGoto 6<cr>", desc = "Buffer 6", silent = true },
    { "<A-7>", "<cmd>BufferGoto 7<cr>", desc = "Buffer 7", silent = true },
    { "<A-8>", "<cmd>BufferGoto 8<cr>", desc = "Buffer 8", silent = true },
    { "<A-9>", "<cmd>BufferGoto 9<cr>", desc = "Buffer 9", silent = true },
    { "<A-0>", "<cmd>BufferLast<cr>", desc = "Last buffer", silent = true },
    { "<A-c>", "<cmd>BufferClose<cr>", desc = "Close buffer", silent = true },
    { "<C-p>", "<cmd>BufferPick<cr>", desc = "Pick buffer", silent = true },
    { "<C-S-p>", "<cmd>BufferPickDelete<cr>", desc = "Pick and delete buffer", silent = true },
    { "<leader>bb", "<cmd>BufferOrderByBufferNumber<cr>", desc = "Sort by number", silent = true },
    { "<leader>bn", "<cmd>BufferOrderByName<cr>", desc = "Sort by name", silent = true },
    { "<leader>bd", "<cmd>BufferOrderByDirectory<cr>", desc = "Sort by directory", silent = true },
    { "<leader>bl", "<cmd>BufferOrderByLanguage<cr>", desc = "Sort by language", silent = true },
    { "<leader>bw", "<cmd>BufferOrderByWindowNumber<cr>", desc = "Sort by window", silent = true },
    { "<leader>cl", "<cmd>BufferCloseBuffersLeft<cr>", desc = "Close left buffers", silent = true },
    { "<leader>cr", "<cmd>BufferCloseBuffersRight<cr>", desc = "Close right buffers", silent = true },
    { "<leader>x", "<cmd>bd<cr>", desc = "Delete buffer", silent = true },
  },
}
